### ISSUE TITLE
helm-org-ql-actions still void variable

### ISSUE THREAD

**Issue by kmaasrud** [toshism/org-super-links#17] opened 2020-06-06 21:21 UTC
I've switched to the develop branch and loaded the bug fix, but still no luck... Everything else works well, but as soon as I'm trying to use helm with `sl-link`, it tells me the same

_Originally posted by @kmaasrud in https://github.com/toshism/org-super-links/issues/16#issuecomment-640119718_

**Comment by toshism** [comment] 2020-06-06 21:49
Interesting, I assume you have `org-ql` installed and that `helm-org-ql` works on it's own fine?

**Comment by kmaasrud** [comment] 2020-06-07 06:15
Yep! Both `org-ql` and `helm-org` are installed, and they seem to be working fine. Can't wrap my head around the issue, I've assured several times now that I have upgraded and required the latest versions of this package and its dependencies.

**Comment by toshism** [comment] 2020-06-11 13:57
Hmm... I'm not able recreate this, but I'm also not really happy with the way the optional dependency of helm-org-ql or helm-rifle are handled. I'm considering just making helm-org-ql a hard dependency.

What happens if you call `helm-org-ql` first and then try to call `sl-link`?

**Comment by toshism** [comment] 2020-07-09 14:57
I'm going to close this now as I think it's a duplicate of the solved issue in #19 

@kmaasrud If you are still having problems and the solution there doesn't help feel free to reopen.

**Closed by toshism** 2020-07-09 14:57 UTC
